### ISSUE TITLE
외부에서 접속시, 404 오류

### ISSUE THREAD

**Issue by LeeByeongMuk** [letsescape/strava-docs-kr#19]
- react browser router 사용시 404 오류 개선

**Comment by kimchanhyung98** [comment]
번역 작업 완료시, STRAVA-3 브랜치와 같이 main 반영

**Comment by kimchanhyung98** [comment]
- 404 페이지 제거 후, redirect 처리
- https://developers.stravakr.com/* -> https://developers.strava.com/*
